services:
  eureka-server:
    image: harshitjain011/eureka-server:latest

  api-gateway:
    image: harshitjain011/api-gateway:latest
    environment:
      JWT_SECRET: ${JWT_SECRET}

  auth-service:
    image: harshitjain011/auth-service:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-abcd}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-abcd}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}

  restaurant-service:
    image: harshitjain011/restaurant-service:latest
    environment:
      JWT_SECRET: ${JWT_SECRET}

  menu-service:
    image: harshitjain011/menu-service:latest
    environment:
      JWT_SECRET: ${JWT_SECRET}

  cart-service:
    image: harshitjain011/cart-service:latest
    environment:
      JWT_SECRET: ${JWT_SECRET}

  order-service:
    image: harshitjain011/order-service:latest
    environment:
      ORDER_DB_PASSWORD: ${MYSQL_PASSWORD:-abcd}
      JWT_SECRET: ${JWT_SECRET}

  payment-service:
    image: harshitjain011/payment-service:latest
    environment:
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
      JWT_SECRET: ${JWT_SECRET}

  delivery-service:
    image: harshitjain011/delivery-service:latest
    environment:
      JWT_SECRET: ${JWT_SECRET}

  review-service:
    image: harshitjain011/review-service:latest
    environment:
      JWT_SECRET: ${JWT_SECRET}

  tracking-service:
    image: harshitjain011/tracking-service:latest

  frontend:
    image: harshitjain011/frontend:latest

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-abcd}
