package com.quickbite.cart.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CartItem {

    private Long id;
    private Long menuItemId;
    private String itemName;
    private String imageUrl;
    private double unitPrice;
    private int quantity;

    // getters and setters generated by Lombok
}
