package com.quickbite.cart.model;

import jakarta.persistence.*;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.util.UUID;
import java.util.ArrayList;
import java.util.List;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "carts", indexes = {
    @Index(name = "idx_user_email", columnList = "user_email"),
    @Index(name = "idx_restaurant_id", columnList = "restaurant_id")
})
@Getter
@Setter
@NoArgsConstructor
public class CartEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_email", nullable = false, unique = true)
    private String userEmail;

    @Column(name = "user_id", nullable = false, unique = true)
    private UUID userId;

    @Column(name = "restaurant_id")
    private Long restaurantId;

    @Column(name = "restaurant_name")
    private String restaurantName;

    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<CartItemEntity> items = new ArrayList<>();

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    @Column(name = "updated_at")
    private LocalDateTime updatedAt = LocalDateTime.now();

    // Constructors
    public CartEntity(String userEmail, Long restaurantId) {
        this.userEmail = userEmail;
        this.userId = buildStableUserId(userEmail);
        this.restaurantId = restaurantId;
    }

    // custom setter logic preserved for userEmail; other getters/setters generated by Lombok

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
        if (this.userId == null) {
            this.userId = buildStableUserId(userEmail);
        }
    }


    @PrePersist
    public void ensureLegacyUserId() {
        if (userId == null && userEmail != null && !userEmail.isBlank()) {
            userId = buildStableUserId(userEmail);
        }
    }

    private static UUID buildStableUserId(String userEmail) {
        return UUID.nameUUIDFromBytes(userEmail.toLowerCase().getBytes(StandardCharsets.UTF_8));
    }
}

