package com.quickbite.cart.model;

import java.util.ArrayList;
import java.util.List;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Cart {

    private String userEmail;
    private Long restaurantId;
    private String restaurantName;
    private final List<CartItem> items = new ArrayList<>();

    // getters and setters generated by Lombok
}
