package com.quickbite.order.entity;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "orders")
@Getter
@Setter
public class OrderEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "order_reference", nullable = false, unique = true, length = 64)
    private String orderReference;

    @Column(name = "user_email", nullable = false, length = 255)
    private String userEmail;

    @Column(name = "restaurant_name", nullable = false, length = 255)
    private String restaurantName;

    @Column(name = "delivery_address", nullable = false, columnDefinition = "TEXT")
    private String deliveryAddress;

    @Column(name = "payment_mode", length = 32)
    private String paymentMode;

    @Column(name = "payment_status", length = 32)
    private String paymentStatus;

    @Column(name = "razorpay_order_id", length = 128)
    private String razorpayOrderId;

    @Column(name = "razorpay_payment_id", length = 128)
    private String razorpayPaymentId;

    @Column(name = "delivery_status", nullable = false, length = 32)
    private String deliveryStatus;

    @Column(name = "delivery_agent_id", length = 64)
    private String deliveryAgentId;

    @Column(name = "delivery_agent", length = 255)
    private String deliveryAgent;

    @Column(name = "eta_minutes", nullable = false)
    private int etaMinutes;

    @Column(name = "total", nullable = false)
    private double total;

    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<OrderItemEntity> items = new ArrayList<>();

    // getters and setters generated by Lombok
}

